[build-system]
requires = ["setuptools>=80.0"]
build-backend = "setuptools.build_meta"

[project]
name = "spam-classifier"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "dotenv>=0.9.9",
    "google-api-python-client>=2.196.0",
    "google-auth-httplib2>=0.4.0",
    "google-auth-oauthlib>=1.4.0",
    "jupyter>=1.1.1",
    "lxml>=6.1.1",
    "matplotlib>=3.11.0",
    "pandas>=3.0.3",
    "scikit-learn>=1.9.0",
    "sqlalchemy>=2.0.49",
]

[project.scripts]
ingest-emails = "scripts.ingest_emails:main"
create-test-set = "scripts.create_test_set:main"
create-train-version = "scripts.create_train_version:main"
get-train-versions = "scripts.get_train_versions:main"
remove-train-version = "scripts.remove_train_version:main"

[tool.uv]
package = true

[tool.setuptools.packages.find]
where = ["."]
include = ["src*", "scripts*"]
